### ISSUE TITLE
Make this module requireable

### ISSUE THREAD

**Issue by boennemann** [alrra/travis-after-all#2]
Hey @alrra,

Up to this point I have used [travis_after_all](https://github.com/dmakhno/travis_after_all) to support multi-job npm deploys in [semantic-release](https://github.com/semantic-release/semantic-release).

As the setup is tedious and requires fiddling with the .travis.yml by hand I wanted to reimplement `travis_after_all` with node myself so I can automatically make it part of semantic-release.
I was super happy to find out that you already did just that.

In order for me to use this module I would love to be able to require this module and get a callback with the results, instead of only using this on the command line and relying on the exit code.

Is this something you would want to support, or merge into this module?

**Comment by alrra** [comment]
@boennemann Thanks for opening this issue!

>  I have used travis_after_all to support multi-job npm deploys in semantic-release.

I've been using the same script in the past, but unfortunately it has some limitations (e.g.: [in order for it to work the tests from the first job need to pass](https://github.com/dmakhno/travis_after_all/blob/5acf1b8d164e7da313f72a8634bdd95182f890f5/travis_after_all.py#L23), if you're not careful, it can [leak private information](https://github.com/Modernizr/Modernizr/commit/851daf9bb234d111fd12c6090fe33e1f47650133), etc.). Also, [it doesn't seem to be maintained anymore](https://github.com/dmakhno/travis_after_all/pull/1). :(

>  fiddling with the .travis.yml by hand

Either way, as far as I can tell, you will still need to edit the `.travis.yml` file because the required `TRAVIS_TEST_RESULT` environment variable is set only in certain stages of [Travis' build lifecycle (e.g.: in `after_script`]((http://docs.travis-ci.com/user/customizing-the-build/#The-Build-Lifecycle))). So, the script that includes this one will still need to be specified in, for example, `after_script`.

> Is this something you would want to support, or merge into this module?

I'll look into it, but that will probably be next week. 

(Note: My main concern so far was to make if work even if people don't use `node`).

**Comment by boennemann** [comment]
> As far as I can tell, you will still need to edit the .travis.yml file because the required TRAVIS_TEST_RESULT environment variable is set only in certain stages of Travis' build lifecycle (e.g.: in after_script). So, the script that will use this one still needs to be specified in, for example, after_script.

Sorry for being unspecific here. I require one script running in the after_script already, but I don't want that my users have to set up more than one. Consuming the functionality of your script would be the ideal way to hide away complexity they shouldn't have to deal with on their own.

> My main concern so far was to make it work even if people don't use node.

I see and it makes total sense. Maybe you can only implicitly run the script if there is no `module.parent` and export the function otherwise.

**Comment by alrra** [comment]
> Sorry for being unspecific here. I require one script running in the after_script already, but I don't want that my users have to set up more than one. Consuming the functionality of your script would be the ideal way to hide away complexity they shouldn't have to deal with on their own.

@boennemann Thanks for clarifying!!

**Comment by alrra** [comment]
> Maybe you can only implicitly run the script if there is no module.parent and export the function otherwise.

I'll probably have some free time over the weekend and I'll see what I can do.

**Comment by alrra** [comment]
@boennemann Done! Sorry for the delay.

If you find something that doesn't work or that can be improved, let me know. :)

**Comment by boennemann** [comment]
Speaking of delay… Sorry for taking so long, but I finally had the time to implement this in my library and it's been super smooth and made my life easier. Thanks for this feature :+1: :sparkles: 

https://github.com/semantic-release/semantic-release/releases/tag/v4.3.2

**Comment by ssbarnea** [comment]
Hi! Could one of you explain me the reasons for reimplementing travis-after-all in JavaScript instead of Python? I observed some problems with my usage of the python script and I am wondering if this one should solve them.

Also the original Travis issue https://github.com/travis-ci/travis-ci/issues/929 seems to include nothing about the JS implementation.

**Comment by alrra** [comment]
>  reimplementing travis-after-all 

@ssbarnea Because I personally wasn't satisfied with the [`travis_after_all`](https://github.com/dmakhno/travis_after_all) script due to the reasons specified in my [previous comment](https://github.com/alrra/travis-after-all/issues/2#issuecomment-124151224).

>  reimplementing travis-after-all in JavaScript instead of Python

* I haven't worked with Python in a long time and I am more comfortable with using JavaScript
* JavaScript is a more popular language, so theoretically, it would be easier for more people to understand what I did and maybe even contribute

> Also the original Travis issue travis-ci/travis-ci#929 seems to include nothing about the JS implementation. 

This script is basically my temporary (unofficial) workaround for that issue. I do not have anything to do with the Travis team. Also, as far as I know, most of Travis is implemented using `ruby`.

> I observed some problems with my usage of the python script and I am wondering if this one should solve them.

Can you be more specific?
