### ISSUE TITLE
Why not check completion from the last job, instead of the first?

### ISSUE THREAD

**Issue by Billiam** [alrra/travis-after-all#22]
If your test matrix is roughly balanced, would it make sense to wait for all jobs to complete from the last job instead of the first? 

If any tests have had to wait in the queue, the last job is most likely to complete last, and would spend the least time waiting for other jobs to complete, freeing up workers.

Just wondering if there's a reason you'd already considered.

[edit] I'm using after-all for deployment, updated language to be generic

**Comment by alrra** [comment]
> would it make sense to wait for all jobs to complete from the last job instead of the first?
> the last job is most likely to complete last, and would spend the least time waiting for other jobs to complete,

@Billiam Are you sure your are not using some [other script](https://github.com/dmakhno/travis_after_all/tree/bd6683ebdd522b77505d3133cad8e14998ee33af#usage)?

I'm asking because this script doesn't wait from the first job, nor the last, and instead it tries to make partial decisions and free up Travis CI workers as soon as possible.

> If any tests have had to wait in the queue, the last job is most likely to complete last

"most likely" probably, but that's not the general case (e.g.: from what I've seen workers for `ubuntu` jobs are allocated faster than for `osx` ones).
